### PR TITLE
Added new features and cleaned code

### PR DESCRIPTION
**Pull request by Unknown66**
Features:
-Multiple pokemon can be observed.
-Language selection per user. (uses pogom languages)
-Save command to be able to add pokemon after restart. (prints /add cmd)
-Added config-bot.json to configure this telegrambot.

Other:
-Updated README.md to latest changes.
-Cleaned code.
-fixed disappear time
-Improved sqlite querys.

### CODE REVIEW

**Comment by Korzakov** [comment]
Nice one! Maybe it would also be nice to have a possibity to send notification as text, so u can see direct in the push message on your phone which pokemon appeared. In that case you could send a link to google maps.

Also it would be nice to show both the disappear time and the remaining minutes until dissapear.

Maybe a message like this:
`"A wild <pokemon_name> has appeared! Available until <24h_time> (<time_left>). <gmaps_link>"`

**Comment by Unknown66** [comment]
You could create an Issue for this but this shouldn't be much effort to accomplish this.

Could be a new command to swap between current mode and yours.
like: /textonly 1 /textonly 0

**Comment by eugenio412** [comment]
Great work @unknown66, I'll test your code tomorrow morning (I'm in Europe) it it works I'll merge it right away! 👍🏻

**Comment by Unknown66** [comment]
Thanks! I'm living in Europe too. :+1:

**Pull request merged**
