### PR TITLE
Location based searching

### PR DESCRIPTION
**Pull request by wardsimon**
Loving the latest commit, it makes work so much easier!

I've added the ability for users to send locations and to search for pokemon within that search radius. Particularly  helpful for those with large scan areas and want to customise locations. At the moment it works only with the telegram send location feature, but can be possibly be updated to do a search of a user supplied string.

Location filtering works and loading of previous user preferences works etc. 
Please test to see if there is anything I've missed.

### CODE REVIEW

**Comment by wardsimon** [comment]
You only want to use commit c8add90ce5485440a9328dd997052fd027cec2ef . All the rest are me being a git noob!

**Comment by Unknown66** [comment]
First of all cool thing! Wanted to implement it too :+1: 

A little thing you should add your commands to `cmd_help`  this way the user will know that they're available.

And I think it would be better to have the ability to set meters instead of km don't you?

**Comment by eugenio412** [comment]
Good job, I'm going to try it soon!

**Comment by wardsimon** [comment]
Oh, I should say...

In the new files DataSources/DSPokemonGoMap*.py there is a problem when catching the exception. The variable chat_id is not in this scope (Unless I'm mistaken) , so an error can occur.

**Comment by Unknown66** [comment]
You're right will fix it after your commits are merged.

**Comment by eugenio412** [comment]
Tested and it works like a charm, I could merge it right away, @Unknown66 do you want to test something first? you can also do a commit to Location branch of @simonward86 so it's merged together

**Comment by Unknown66** [comment]
Merge it first it's not a big bug. I will do the fix later :+1:

**Comment by eugenio412** [comment]
Well, merged, @simonward86 , you earned the collaborator status :smile:

**Pull request merged**
